# Generated by Django 3.0.6 on 2020-05-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('comment_date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
