# Generated by Django 3.0.6 on 2020-05-28 01:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='contact',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='about_app_content_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content on About Application section'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='about_app_content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content on About Application section'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='about_me_content_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content on About me section'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='about_me_content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content on About me section'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='full_name_az',
            field=models.CharField(default='Bakir Yunusov', max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='full_name_en',
            field=models.CharField(default='Bakir Yunusov', max_length=255, null=True, verbose_name='Full name'),
        ),
    ]
