# Generated by Django 3.0.6 on 2020-05-22 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='social_accounts',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Website_Settings'),
        ),
        migrations.AddField(
            model_name='permitted_user',
            name='comment_allowed_users',
            field=models.ManyToManyField(blank=True, related_name='comment_allowed_users', to=settings.AUTH_USER_MODEL, verbose_name='Comment-allowed users'),
        ),
        migrations.AddField(
            model_name='permitted_user',
            name='read_only_users',
            field=models.ManyToManyField(blank=True, related_name='read_only_users', to=settings.AUTH_USER_MODEL, verbose_name='Read-only users'),
        ),
        migrations.AddField(
            model_name='permitted_user',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
