# Generated by Django 3.0.6 on 2020-05-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200519_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
