# Generated by Django 3.0.6 on 2020-05-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200523_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('1', 'Header'), ('2', 'Footer'), ('3', 'Both'), ('4', 'Useful Links')], help_text='1 => Header\n 2 => Footer \n 3 => Both \n 4 => Useful Links', max_length=50, verbose_name='Position'),
        ),
    ]
