# Generated by Django 3.0.6 on 2020-05-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200523_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_settings',
            name='notification_text_less_ten_min',
            field=models.TextField(default='You have less 10 minutes left to finish your task.', verbose_name='Notification Text'),
        ),
        migrations.AddField(
            model_name='website_settings',
            name='notification_text_on_time',
            field=models.TextField(default='You have 10 minutes left to finish your task.', verbose_name='Notification Text'),
        ),
    ]
