# Generated by Django 3.0.6 on 2020-05-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200523_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_settings',
            old_name='notification_text_less_ten_min',
            new_name='notification_text',
        ),
        migrations.RemoveField(
            model_name='website_settings',
            name='notification_text_on_time',
        ),
    ]
