# Generated by Django 3.0.6 on 2020-05-20 02:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_message_socialaccounts_websitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Settings', 'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='about_app_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content on About Application section'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='about_me_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content on About me section'),
        ),
    ]
