# Generated by Django 3.0.6 on 2020-05-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200520_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccounts',
            name='i_tag_class_on_about_me',
            field=models.CharField(default=1, help_text='Example: icofont-facebook', max_length=255, verbose_name='I tag class name on About me section'),
            preserve_default=False,
        ),
    ]
