# Generated by Django 3.0.6 on 2020-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_socialaccounts_i_tag_class_on_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Photo'),
        ),
    ]
