# Generated by Django 3.0.6 on 2020-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_websitesettings_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='full_name',
            field=models.CharField(default='Bakir Yunusov', max_length=255, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='position',
            field=models.CharField(default='Python Developer', max_length=255, verbose_name='Position'),
        ),
    ]
