# Generated by Django 3.0.6 on 2020-05-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200520_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccounts',
            new_name='Social_Accounts',
        ),
        migrations.RenameModel(
            old_name='WebsiteSettings',
            new_name='Website_Settings',
        ),
    ]
