# Generated by Django 3.0.6 on 2020-05-24 03:20

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='Comment content')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comment date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('comment_date',),
            },
        ),
        migrations.CreateModel(
            name='Permitted_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permitted User',
                'verbose_name_plural': 'Permitted Users',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(max_length=300, verbose_name='Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('date_created',),
            },
        ),
    ]
