# Generated by Django 3.0.6 on 2020-05-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20191010_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='permitted_users',
            options={'verbose_name': 'Permitted User', 'verbose_name_plural': 'Permitted Users'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.CreateModel(
            name='Permitted_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_allowed_users', models.ManyToManyField(blank=True, related_name='comment_allowed_users', to=settings.AUTH_USER_MODEL)),
                ('read_only_users', models.ManyToManyField(blank=True, related_name='read_only_users', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'verbose_name': 'Permitted User',
                'verbose_name_plural': 'Permitted Users',
            },
        ),
    ]
