# Generated by Django 3.0.6 on 2020-05-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200513_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permitted_Users',
        ),
    ]
